[Migration]
Hash = "5110293183485849398"
Initial = false
Dependency = 2
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "cnamerelation"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations]]
Type = "CreateModel"
Name = "domainhostrelation"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "is_direct"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domainhostrelation"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "domain"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "domainhostrelation"

[Migration.Operations.Field]
Name = "host"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "host"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "cnamerelation"

[Migration.Operations.Field]
Name = "source"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "domain"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "cnamerelation"

[Migration.Operations.Field]
Name = "destination"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "domain"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"
