---
- kraken_db_name: "kraken"
  kraken_db_user: "kraken"
  kraken_db_password: ""
  kraken_secret_key: ""
  kraken_reporting_key: ""
  origin_uri: "https://kraken.test"
  server_name: "kraken.test"
  leech_db_name: "leech"
  leech_db_user: "leech"
  leech_db_password: ""
  leech_token: ""