[package]
name = "probe-config"
version = "0.1.0"
edition = "2021"
authors = ["gammelalf <gammelalf@hopfen.space>", "Niklas Pfister <git@omikron.dev>"]
license = "AGPL-3.0"

[dependencies]
regex = { version = "~1" }
log = { version = "~0.4" }